title: "willclark.tech"
description: "return tech || nonsense"
production_url: "https://blog.willclark.tech"
author:
  name: "Will Clark"
  website: "willclark.tech"
  email: "will@willclark.tech"
  github: "willclarktech"
  twitter: "willclarktech"

theme: "jekyll-theme-cayman"
paginate: 10

google_analytics: "UA-69040906-1"
disqus_short_name: "willclarktech"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "CNAME"
  - "README.md"
  - "scripts/"
